import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function getTargetDir(startDir) {
  let dir = startDir;
  while (dir !== path.parse(dir).root) {
    if (fs.existsSync(path.join(dir, "package.json")) && !dir.includes("node_modules")) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  return process.cwd();
}

const projectRoot = getTargetDir(__dirname);
const packageJsonPath = path.join(projectRoot, "package.json");

// 🪄 Auto-create package.json if it doesn't exist
if (!fs.existsSync(packageJsonPath)) {
  const pkg = {
    name: "my-project",
    version: "1.0.0",
    private: true,
    description: "Auto-generated by Claude skills installer",
  };
  fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2));
  console.log("🧩 No package.json found — created a new one automatically.");
}

const packageSkillsDir = path.join(__dirname, "dist", "skills");
const claudeDir = path.join(projectRoot, ".claude");
const skillsDir = path.join(claudeDir, "skills");

function copyRecursive(src, dest) {
  if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
  for (const item of fs.readdirSync(src)) {
    const srcPath = path.join(src, item);
    const destPath = path.join(dest, item);
    const stat = fs.statSync(srcPath);
    if (stat.isDirectory()) copyRecursive(srcPath, destPath);
    else fs.copyFileSync(srcPath, destPath);
  }
}

(async () => {
  try {
    fs.mkdirSync(skillsDir, { recursive: true });
    console.log(`📁 .claude/skills will be installed at: ${skillsDir}`);

    if (fs.existsSync(packageSkillsDir)) {
      console.log("📦 Copying Claude skills...");
      copyRecursive(packageSkillsDir, skillsDir);
      console.log("✅ Skills installed successfully!");
    } else {
      console.warn("⚠️ No dist/skills folder found — did you build it?");
    }
  } catch (err) {
    console.error("❌ Error installing skills:", err);
  }

  console.log("✨ Claude skill installation complete!");
})();
