import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 🧭 Find the nearest project root (avoid node_modules)
function findProjectRoot(startDir) {
  let dir = startDir;
  while (dir !== path.parse(dir).root) {
    if (fs.existsSync(path.join(dir, "package.json")) && !dir.includes("node_modules")) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  return process.cwd();
}

const projectRoot = findProjectRoot(__dirname);
const packageJsonPath = path.join(projectRoot, "package.json");

// 🪄 Auto-create package.json if missing
if (!fs.existsSync(packageJsonPath)) {
  const pkg = {
    name: "my-project",
    version: "1.0.0",
    private: true,
    description: "Auto-generated by Claude skills installer",
  };
  fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2));
  console.log("🧩 No package.json found — created one automatically.");
}

// 🗂️ Paths
const distSkillsDir = path.join(__dirname, "dist", "skills");
const claudeDir = path.join(projectRoot, ".claude");
const targetSkillsDir = path.join(claudeDir, "skills");

// 🪞 Recursive copy helper
function copyRecursive(src, dest) {
  if (!fs.existsSync(src)) {
    console.warn(`⚠️ Source folder not found: ${src}`);
    return;
  }
  fs.mkdirSync(dest, { recursive: true });
  for (const item of fs.readdirSync(src)) {
    const srcPath = path.join(src, item);
    const destPath = path.join(dest, item);
    const stat = fs.statSync(srcPath);

    // Skip node_modules from being copied
    if (item === "node_modules") continue;

    if (stat.isDirectory()) copyRecursive(srcPath, destPath);
    else fs.copyFileSync(srcPath, destPath);
  }
}

(async () => {
  try {
    console.log(`📁 Installing Claude skills to: ${targetSkillsDir}`);
    fs.mkdirSync(targetSkillsDir, { recursive: true });

    if (fs.existsSync(distSkillsDir)) {
      copyRecursive(distSkillsDir, targetSkillsDir);
      console.log("✅ Claude skills copied successfully!");
    } else {
      console.warn("⚠️ No dist/skills directory found — did you run `npm run build`?");
    }

    // Optionally hide internal node_modules
    const nodeModulesPath = path.join(projectRoot, "node_modules");
    if (fs.existsSync(nodeModulesPath)) {
      try {
        fs.renameSync(nodeModulesPath, path.join(projectRoot, ".node_modules_hidden"));
        console.log("🙈 node_modules renamed to .node_modules_hidden for cleanliness.");
      } catch (err) {
        console.warn("⚠️ Couldn't hide node_modules:", err.message);
      }
    }
  } catch (err) {
    console.error("❌ Error installing skills:", err);
  }

  console.log("✨ Claude skill installation complete!");
})();
